title: "Ouaisfi·eu - juste pour info"
author: "Cellule Analyse"
url: "https://ouaisfieu.github.io"   # Root GitHub Pages
description: >
  Dossiers thématiques libres (Citoyenneté, info & pouvoir d’agir)

remote_theme: "abhinavs/moonwalk"     # Moonwalk côté GitHub
permalink: "/:slug"
favicon: "/assets/img/logo.png"

twitter:
  username: ouaisfieu
  card: summary_large_image

theme_config:
  appearance: "dark"
  appearance_toggle: false
  back_home_text: "Accueil"
  date_format: "%d %b %Y"
  show_description: true
  show_navbar: true
  show_footer: true
  show_projects: true
  show_blog: true
  show_old_projects: false
  show_misc_list: false
  show_reading_time: false
  show_tags: false
  home:
    title_projects: Les dossiers
    title_blog: Journal

plugins:                     # compatibles GitHub Pages
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-remote-theme       # déjà implicite, mais on l’affiche
